version: "3.8"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules # Anonymous volume for node_modules
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    restart: unless-stopped
