# Use the official Node.js image as the base image
FROM node:20.7.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy all files
COPY . .

# Set environment variables
ENV PORT=3000

# Expose the port
EXPOSE 3000

# Define the entrypoint command
CMD ["node", "./server/dist/server.js"]

ENTRYPOINT [ "node", "./server/dist/server.js" ]