version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - /app/client/node_modules
      - /app/server/node_modules
    env_file:
      - server/.env
    ports:
      - "3000:3000" # Client port
      - "443:443"   # Server port
