version: '3'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - server/.env

  client:
    build: ./client
    ports:
      - "8080:80"
    environment:
    - API_URL=http://server:3000
