# Use the official Node.js image as the base image
FROM node:18

# RUN a command to npm install webpack globally in the container
RUN npm install -g webpack

# Set up a WORKDIR for application in the container
WORKDIR /usr/src/app

# COPY your package*.json (to get both package and package-lock) files to the WORKDIR in the container
COPY package*.json /usr/src/app/

# RUN a command to npm install your node_modules in the container
RUN npm i

# EXPOSE your server port
EXPOSE 8080