# Stage 1: Client Development Setup
FROM node:20 AS client-dev
WORKDIR /app/client
COPY ./client/package*.json ./
RUN npm install
COPY ./client/ .

# Stage 2: Server Development Setup
FROM node:20 AS server-dev
WORKDIR /app/server
COPY ./server/package*.json ./
RUN npm install
COPY ./server/ .

# Development Stage
FROM node:20 AS development
WORKDIR /app
# Copy client and server directories
COPY package*.json ./
RUN npm install
COPY --from=client-dev /app/client ./client
COPY --from=server-dev /app/server ./server
# Rebuild bcrypt for linux
RUN cd ./server && npm rebuild bcrypt
# Expose the port the app runs in
EXPOSE 3000
EXPOSE 443

# Start development
CMD ["npm", "run", "dev"]
