FROM node:20-slim

ENV NODE_ENV=development

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install build essentials for bcrypt
RUN apt-get update && apt-get install -y python3 make g++

# Clean install dependencies
RUN npm ci
RUN npm rebuild bcrypt --build-from-source

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]