version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    ports:
      - "443:443" # Server port
    restart: unless-stopped
