version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules # Anonymous volume for node_modules
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
